### ISSUE TITLE
Out of memory issue

### ISSUE THREAD

**Issue by xliu38** [broadinstitute/SignatureAnalyzer-GPU#21]
Hi SignatureAnalyzer Team,

Thank you for the impressive work and continuous maintenance of the tool! 

I was interested in running this on very large single-cell RNA-seq datasets, so I tested on a simulated scRNA-seq dataset (using Splatter) with 1M cells and 25k genes. In specific, I am running on cluster node with Nvidia A100 GPU and 80GB of memory. Unfortunately, I got a CUDA out of memory error (pasted below). 

> Traceback (most recent call last):
>   File "SignatureAnalyzer-GPU.py", line 263, in <module>
>     main()
>   File "SignatureAnalyzer-GPU.py", line 258, in main
>     args.report_frequency,
>   File "/research/rgs01/home/clusterHome/xliu38/SignatureAnalyzer-GPU/ARD_NMF.py", line 227, in run_method_engine
>     W,H,V,Lambda,C,b0,eps_,phi,mask = results.W.cuda(cuda_string),results.H.cuda(cuda_string),results.V.cuda(cuda_string),results.Lambda.cuda(cuda_string),results.C.cuda(cuda_string),results.b.cuda(cuda_string),results.eps_.cuda(cuda_string),results.phi.cuda(cuda_string),results.mask.cuda(cuda_string)
> torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 93.23 GiB (GPU 0; 79.32 GiB total capacity; 784.00 MiB already allocated; 77.62 GiB free; 784.00 MiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

Could you let me know if I am calling the function properly? 
`python SignatureAnalyzer-GPU.py --data counts.npz --max_iter=100000 --output_dir Splat_1m --K0 200 --prior_on_W L1 --prior_on_H L2 --labeled `

In addition, I wonder if there is a suggested choice on initial value of K0? It seems like it starts from number of genes by default, which will take a while to run. 

Thanks,
Xueying

**Comment by francois-a** [comment]
To avoid running out of memory you'll need to reduce the size of the input. Including all ~25k genes is unlikely to be informative, so you can subset genes using variable gene selection approaches as implemented in scanpy or Seurat, for example. If that isn't sufficient, you could consider averaging the expression across small numbers of cells.

For K0 you'll need to experiment as well, but a value between 50-100 should be reasonable (in the [paper](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-019-1836-7) we found 32 signatures for the 1M cells mouse dataset).

**Comment by xliu38** [comment]
Thank you for the clarification! 

> To avoid running out of memory you'll need to reduce the size of the input. Including all ~25k genes is unlikely to be informative, so you can subset genes using variable gene selection approaches as implemented in scanpy or Seurat, for example. If that isn't sufficient, you could consider averaging the expression across small numbers of cells.
> 
> For K0 you'll need to experiment as well, but a value between 50-100 should be reasonable (in the [paper](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-019-1836-7) we found 32 signatures for the 1M cells mouse dataset).
